# Generated by Django 3.2 on 2023-12-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano', models.DateField()),
                ('albunes_imagen', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('artista_imagen', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo_mp3', models.BinaryField()),
                ('archivo_img', models.BinaryField()),
                ('duracion', models.TimeField()),
                ('albun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.albun')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.artista')),
            ],
        ),
    ]
