# Generated by Django 3.2 on 2023-12-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo_img',
            field=models.ImageField(upload_to='canciones/imagenes/'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='archivo_mp3',
            field=models.FileField(upload_to='canciones/mp3/'),
        ),
    ]
