# Generated by Django 3.2 on 2023-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20231217_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albun',
            name='albunes_imagen',
            field=models.ImageField(upload_to='canciones/imagenes/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='artista_imagen',
            field=models.ImageField(upload_to='canciones/imagenes/'),
        ),
    ]
